version: '3.7'

services:
  db_migrate:
    build:
      context: .
      dockerfile: docker/db_migrate.dockerfile
    environment:
      - ENV=production
    volumes:
      - db:/app/db:rw

  url_shortener:
    build:
      context: .
      dockerfile: docker/url_shortener.dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - SERVER_NAME=ec2-3-38-149-36.ap-northeast-2.compute.amazonaws.com
      - SSL_ENABLED=false
    volumes:
      - db:/app/db:rw
    depends_on:
      - db_migrate

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled

volumes:
  db: