---
- name: Setup NGINX reverse proxy for Docker container
  hosts: url_shortener
  become: yes
  tasks:
      - name: Install required packages
        apt:
            name: "{{ item }}"
            state: present
        loop:
            - nginx
            - docker.io
            - docker-compose

      - name: Start Docker service
        service:
            name: docker
            state: started

      - name: Synchronize local directory to remote directory
        synchronize:
            src: "{{ ansible_env.PWD }}"
            dest: "/app"
            rsync_opts:
                - "--exclude-from=.dockerignore"

      - name: Build Docker container
        command: "docker-compose -f "/app/docker-compose.yml" up -d"
        become: yes

